from __future__ import annotations

MetricLayoutSpec = tuple[str, int, int, int, int]

METADATA_LAYOUTS: dict[str, list[MetricLayoutSpec]] = {
    "wide": [
        ("meta_bank_name", 0, 0, 1, 2),
        ("meta_account_name", 0, 2, 1, 2),
        ("meta_period", 0, 4, 1, 2),
        ("meta_account_number", 1, 0, 1, 2),
        ("meta_account_type", 1, 2, 1, 1),
        ("meta_currency", 1, 3, 1, 1),
        ("meta_tax_code", 1, 4, 1, 2),
        ("meta_opening_balance", 2, 0, 1, 2),
        ("meta_actual_balance", 2, 2, 1, 2),
        ("meta_closing_balance", 2, 4, 1, 2),
        ("meta_total_debits", 3, 0, 1, 1),
        ("meta_total_credits", 3, 1, 1, 1),
        ("meta_total_fees", 3, 2, 1, 1),
        ("meta_total_vat", 3, 3, 1, 1),
        ("meta_total_debit_tx", 3, 4, 1, 1),
        ("meta_total_credit_tx", 3, 5, 1, 1),
    ],
    "medium": [
        ("meta_bank_name", 0, 0, 1, 2),
        ("meta_account_name", 0, 2, 1, 2),
        ("meta_period", 1, 0, 1, 2),
        ("meta_account_number", 1, 2, 1, 1),
        ("meta_tax_code", 1, 3, 1, 1),
        ("meta_account_type", 2, 0, 1, 1),
        ("meta_currency", 2, 1, 1, 1),
        ("meta_opening_balance", 2, 2, 1, 1),
        ("meta_actual_balance", 2, 3, 1, 1),
        ("meta_closing_balance", 3, 0, 1, 1),
        ("meta_total_debits", 3, 1, 1, 1),
        ("meta_total_credits", 3, 2, 1, 1),
        ("meta_total_fees", 3, 3, 1, 1),
        ("meta_total_vat", 4, 0, 1, 1),
        ("meta_total_debit_tx", 4, 1, 1, 1),
        ("meta_total_credit_tx", 4, 2, 1, 1),
    ],
    "narrow": [
        ("meta_bank_name", 0, 0, 1, 3),
        ("meta_account_name", 1, 0, 1, 3),
        ("meta_period", 2, 0, 1, 2),
        ("meta_currency", 2, 2, 1, 1),
        ("meta_account_number", 3, 0, 1, 1),
        ("meta_account_type", 3, 1, 1, 1),
        ("meta_tax_code", 3, 2, 1, 1),
        ("meta_opening_balance", 4, 0, 1, 1),
        ("meta_actual_balance", 4, 1, 1, 1),
        ("meta_closing_balance", 4, 2, 1, 1),
        ("meta_total_debits", 5, 0, 1, 1),
        ("meta_total_credits", 5, 1, 1, 1),
        ("meta_total_fees", 5, 2, 1, 1),
        ("meta_total_vat", 6, 0, 1, 1),
        ("meta_total_debit_tx", 6, 1, 1, 1),
        ("meta_total_credit_tx", 6, 2, 1, 1),
    ],
    "compact": [
        ("meta_bank_name", 0, 0, 1, 2),
        ("meta_account_name", 1, 0, 1, 2),
        ("meta_period", 2, 0, 1, 2),
        ("meta_account_number", 3, 0, 1, 1),
        ("meta_tax_code", 3, 1, 1, 1),
        ("meta_account_type", 4, 0, 1, 1),
        ("meta_currency", 4, 1, 1, 1),
        ("meta_opening_balance", 5, 0, 1, 1),
        ("meta_actual_balance", 5, 1, 1, 1),
        ("meta_closing_balance", 6, 0, 1, 2),
        ("meta_total_debits", 7, 0, 1, 1),
        ("meta_total_credits", 7, 1, 1, 1),
        ("meta_total_fees", 8, 0, 1, 1),
        ("meta_total_vat", 8, 1, 1, 1),
        ("meta_total_debit_tx", 9, 0, 1, 1),
        ("meta_total_credit_tx", 9, 1, 1, 1),
    ],
}

DEFAULT_METRIC_LAYOUT: list[MetricLayoutSpec] = METADATA_LAYOUTS["wide"]
